name: My CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Test My Action
        uses: wordpress/theme-review-action@trunk
        id: test
        with:
          accessible-ready: false
      
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Screenshots
          path: ${{ steps.test.outputs.screenshots }}
